[package]
name = "rtail_kafka"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = { version = "0.38.0", features = ["cmake-build"] }
clap = { version = "4.5.45", features = ["derive"] }
chrono = "0.4.41"